CREATE TABLE[dbo].[People] (
[Id] INT IDENTITY(1, 1) NOT NULL,
[FIO] NVARCHAR(MAX) COLLATE Cyrillic_General_CI_AS NOT NULL,
[Birthday] NVARCHAR(MAX) NULL,
[Email] NVARCHAR(100) NULL,
[Phone] NVARCHAR(MAX) NULL,
CONSTRAINT[PK_dbo.People] PRIMARY KEY CLUSTERED([Id] ASC)
);